In [ ]:
import pandas as pd

books_df = pd.read_csv('books.csv')/
interaction_graph_df = pd.read_csv('interaction_graph.csv')

In [10]:
books_df.head(5)

,product_name,slug,description,price,stock,is_available,images,category_slug,popularity_score,num_purchases,num_views,num_wishlist
0,The Silent Patient,the-silent-patient,A psychological thriller about a woman’s act o...,14.99,23,True,NaN,fiction,0.87,124,520,78
1,Sapiens: A Brief History of Humankind,sapiens-a-brief-history-of-humankind,An exploration of the history and impact of Ho...,21.50,45,True,NaN,non-fiction,0.92,310,1040,132
2,Atomic Habits,atomic-habits,A practical guide to building good habits and ...,17.99,67,True,NaN,business,0.95,520,2100,310
3,Deep Learning with Python,deep-learning-with-python,A comprehensive introduction to deep learning ...,34.50,12,True,NaN,technology,0.81,75,320,55
4,The Second World War,the-second-world-war,An authoritative account of World War II by re...,27.99,34,True,NaN,history,0.77,110,430,60

In [12]:
interaction_graph_df.head(5)

   user_id  product_id interaction_type                         timestamp
0        3           7         wishlist  2025-06-02 00:15:27.428238+00:00
1        3           3             cart  2025-06-02 00:15:27.430068+00:00
2        3           6         wishlist  2025-06-02 00:15:27.432453+00:00
3        3           6             cart  2025-06-02 00:15:27.434089+00:00
4        3           2             view  2025-06-02 00:15:27.436118+00:00

On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   ../pipeline.py
	modified:   ../../templates/store/product_detail.html
	modified:   ../../templates/wishlist/wishlist.html

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	./
	../management/commands/generate_interactions.py
	../management/commands/import_books.py
	../management/commands/import_categories.py
	../../../venv/bin/httpx
	../../../venv/bin/jlpm
	../../../venv/bin/jsonpointer
	../../../venv/bin/jupyter-dejavu
	../../../venv/bin/jupyter-events
	../../../venv/bin/jupyter-execute
	../../../venv/bin/jupyter-lab
	../../../venv/bin/jupyter-labextension
	../../../venv/bin/jupyter-labhub
	../../../venv/bin/jupyter-nbconvert
	../../../venv/bin/jupyter-server
	../../../venv/bin/jupyter-trust
	../../../venv/bin/pybabel
	../../../venv/bin/pyjson5
	../../../venv/bin/send2trash
	../../../venv/bin/wsdump
	../../../venv/etc/
	../../../venv/share/applications/
	../../../venv/share/icons/
	../../../venv/share/jupyter/lab/
	../../../venv/share/jupyter/labextensions/
	../../../venv/share/jupyter/nbconvert/

no changes added to commit (use "git add" and/or "git commit -a")